spring:
    security:
        oauth2:
            client:
                registration:
                    twitch:
                        client-id: ${TWITCH_CLIENT_ID}
                        client-secret: ${TWITCH_CLIENT_SECRET}
                provider:
                    twitch:
                        issuer-uri: https://id.twitch.tv/oauth2